### ISSUE TITLE
generate_figure: Use friendlier names for sites

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/spine-generic#47]
notably, change these:
- GE scanner with current name “brno” to “UHBrno" (University Hospital Brno) or shorter version “UHB" 
- Siemens scanner with current name “brnoPrisma” to “CEITECBrno" (Central European Institute of Technology Brno) or shorter version “CEITEC"

**Comment by valosekj** [comment]
I proposed solution directly inside`generate_figure.py` script. 

But most correct fix of this issue would be to rename source files (nii and json files) in dataset at openneuro.org website, rerun `process_data.sh` and then change names of sites in: https://github.com/sct-pipeline/spine-generic/blob/d51799c7339c1b066d098a1427d9aed7bba3e177/processing/generate_figure.py#L91-L92

We can also consider to rename some another sites which have name of the scanner inside site name (like juntendo750w, vuiisAchieva, beijingPrisma,...) because scanner name is included inside bar plots.

**Comment by valosekj** [comment]
@jcohenadad for final paper´s figures, we could invigorate discussion about names for sites. The easiest solution is probably using "conversion dict", something how I outlined here https://github.com/sct-pipeline/spine-generic/pull/55/files
